=== furyegg/test-java2/test-xml/src/main/java/comparation/book.xsd
<xs:schema targetNamespace="http://www.test.com/book" xmlns="http://www.test.com/book" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="books" type="booksType" />
	<xs:element name="book" type="bookType" />

	<xs:complexType name="booksType">
		<xs:sequence>
			<xs:element ref="book" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="author" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" />
	</xs:complexType>

</xs:schema>

=== furyegg/test-java2/test-xml/src/main/java/comparation/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<bk:books xmlns:bk="http://www.test.com/book" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.test.com/book ./book.xsd">
	<bk:book id="1">
		<bk:name>Name1</bk:name>
		<bk:author>author1</bk:author>
	</bk:book>
	<bk:book id="2">
		<bk:name>Name2</bk:name>
		<bk:author>author2</bk:author>
	</bk:book>
	<bk:book id="3">
		<bk:name>Name3</bk:name>
		<bk:author>author3</bk:author>
	</bk:book>
</bk:books>
